#162170690 Edit user comments(s) on article
andela/balder-ah-frontend pull request #27
Opened 2019-01-30 04:05 UTC by codeshifu

#### What does this PR do?
Allows (authenticated) users edit their previous comment(s) on articles

#### Description of Task to be completed?
Have comment edit working

#### How should this be manually tested?
```bash
git clone git@github.com:andela/balder-ah-frontend.git

cd balder-ah-frontend

npm install

npm start
```
Visit an article page to comment on it and be able to edit it.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories? (If applicable)
[#162170690](https://www.pivotaltracker.com/story/show/162170690)

#### Screenshots (If applicable)
![2019-01-30 04 53 49](https://user-images.githubusercontent.com/5154605/51957580-850f5600-244c-11e9-859e-d717884dfd2a.gif)

#### Questions:
N/A

2019-01-31 07:41 UTC, omokaro-faith requested changes

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/presentation/SmallArticleCard.jsx
> +          <p>I am a very simple card. I am good at containing small bits of information. lorem</p>
Lol. Why did you have to add `lorem` here ?

2019-01-31 07:41 UTC, omokaro-faith commented on src/actions/search.js
> +// eslint-disable-next-line import/prefer-default-export
Please remove this line.

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/comment/Comment.scss
>  }
A new line here, please.

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/comment/CommentList.test.jsx
> +
What about abstracting this into another file.

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/comment/EditCommentForm.scss
> +}
A new line here, please.

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/presentation/NavSearch.scss
> +}
Here also.

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/presentation/Select.scss
> +}
........

2019-01-31 07:41 UTC, omokaro-faith commented on src/components/presentation/SmallArticleCard.jsx
> +          <p>I am a very simple card. I am good at containing small bits of information. lorem</p>
This has not been modified.

2019-01-31 07:41 UTC, omokaro-faith commented
Please resolve conflicts also

2019-01-31 13:15 UTC, akhilome reviewed
This PR still contains two commits.

2019-02-01 04:38 UTC, akhilome requested changes
Please fix conflicts and issue I mentioned above so that I can properly review and approve 💪

2019-02-01 06:22 UTC, codeshifu commented on src/components/presentation/NavSearch.scss
> +}
fixed

2019-02-01 06:22 UTC, luqmanoop commented on src/components/comment/EditCommentForm.scss
> +}
fixed

2019-02-01 06:22 UTC, luqmanoop commented on src/components/comment/Comment.scss
>  }
resolved

2019-02-01 06:22 UTC, luqmanoop commented on src/actions/search.js
> +// eslint-disable-next-line import/prefer-default-export
done

2019-02-01 06:22 UTC, luqmanoop commented on src/components/presentation/SmallArticleCard.jsx
> +          <p>I am a very simple card. I am good at containing small bits of information. lorem</p>
resolved

2019-02-01 09:03 UTC, akhilome approved these changes

2019-02-04 08:26 UTC, frostyblok approved these changes

2019-02-04 09:02 UTC, omokaro-faith approved these changes

2019-02-04 09:03 UTC, omokaro-faith commented
@codeshifu Please resolve conflicts.

2019-02-04 09:51 UTC, oluwajuwon approved these changes
LGTM! 👍

2019-02-06 08:14 UTC, omokaro-faith commented
@codeshifu please resolve conflicts

2019-02-07 10:14 UTC, merged