#162170685 Article should show read time
andela/balder-ah-frontend pull request #29
Opened 2019-01-31 00:41 UTC by oluwajuwon

#### What does this PR do?

This PR enables users see read time of an article

#### Description of Task to be completed?

 - Write test for appropriate component
 - Create read time component

#### How should this be manually tested?
* Clone the repo and `cd` into the folder
* Run `npm install` to install all the dependencies
* Run `npm run start:dev` to start the server
* In your browser visit `localhost:3000/articles/:articleSlug` (a slug of an existing article) or check all the articles via `localhost:3000/articles` the read time should be displayed there

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories? (If applicable)
[#162170685](https://www.pivotaltracker.com/story/show/162170685)

#### Screenshots (If applicable)
<img width="1440" alt="screen shot 2019-01-31 at 1 37 20 am" src="https://user-images.githubusercontent.com/29441898/52022399-0c1a0800-24f9-11e9-92e0-1b3c44a43f14.png">
<img width="1440" alt="screen shot 2019-01-31 at 1 37 44 am" src="https://user-images.githubusercontent.com/29441898/52022402-0c1a0800-24f9-11e9-96c1-353d2cb99fa7.png">

#### Questions:
N/A

2019-01-31 07:22 UTC, omokaro-faith requested changes

2019-01-31 07:22 UTC, omokaro-faith commented on src/components/presentation/ReadTime.jsx
> +          read
Do you really need to put empty strings inside curly braces here?

2019-01-31 07:22 UTC, omokaro-faith commented on src/components/presentation/ReadTime.test.jsx
> +});
LoL. There's no test assertion here.
Please add assertions.

2019-01-31 07:47 UTC, akhilome commented on src/components/presentation/ReadTime.test.jsx
> +});
😁

2019-01-31 08:03 UTC, Johnsonojo commented on src/components/presentation/ArticleCard.jsx
> +  const defaultImg = process.env.REACT_APP_ARTICLE_CARD_DEFAULT_IMG;
Good job renaming the value of `defaultImg`

2019-01-31 08:19 UTC, oluwajuwon commented on src/components/presentation/ReadTime.jsx
> +          read
I've actually found a better way to go about it, I'll make the change now

2019-01-31 08:50 UTC, oluwajuwon commented on src/components/presentation/ReadTime.test.jsx
> +});
I'll work on that right away

2019-01-31 15:33 UTC, frostyblok approved these changes

2019-01-31 15:38 UTC, akhilome approved these changes

2019-01-31 23:27 UTC, luqmanoop approved these changes

2019-02-01 07:36 UTC, omokaro-faith approved these changes

2019-02-01 07:37 UTC, merged